[package]
name = "vulkt"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[dependencies]
glam = "0.25"
log = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
vulkano = "0.34"
vulkano-shaders = "0.34"
winit = "0.28"
